### Get Single Employee
GET http://localhost:8083/employee


### Get All Employees
GET http://localhost:8083/employees


### Add Employee
POST http://localhost:8083/employee
Content-Type: application/json

{
  "id": 104,
  "name": "Rohit",
  "salary": 80000
}


### Update Employee
PUT http://localhost:8083/employee
Content-Type: application/json

{
  "id": 101,
  "name": "Mihir Updated",
  "salary": 90000
}

### Get All Countries
GET http://localhost:8083/countries

### Get Country By Code
GET http://localhost:8083/countries/IN

### Get Country By Code
GET http://localhost:8083/countries/IN


### Invalid Country Code
GET http://localhost:8083/countries/ABC


### Generate JWT Token

POST http://localhost:8083/authenticate
Content-Type: application/json


{
  "username":"mihir",
  "password":"12345"
}


### Get Employees with JWT
GET http://localhost:8083/employees
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtaWhpciIsImlhdCI6MTc4Mzc1ODA0NywiZXhwIjoxNzgzNzYxNjQ3fQ.m3GKev0DCb0TX2A-GHlYX2bVOFr8sVmJSGgOBO1EjT0